### ISSUE TITLE
Use the 'releases' to emit a binary release?

### ISSUE THREAD

**Issue by TurkeyMan** [lhamot/CPP2D#28]
LLVM is a gigantic dependency, and it would be really nice if I didn't have to build this myself to try it out.
There are plenty of CI services that will automate builds and release.

**Comment by lhamot** [comment]
Good idea.
Do you have a suggestion for the CI?
Is travis a good one?

**Comment by TurkeyMan** [comment]
Travis is good for the nix'es. AppVeyor for the windows builds. That would be my go-to.

**Comment by lhamot** [comment]
It will probably need some extra-work later but basically it is done.
